### ISSUE TITLE
Milestone 1: Only logs view with no lazy loading

### ISSUE THREAD

**Issue by callpraths** [callpraths/lorgnette#5]
- [ ] Design: Specify interface boundary between controllers and model, set architectural terminology
- [ ] Plumbing: Rust wasm, component injection, TS controllers
- [ ] Plumbing: Load a file, create a logs view viewport
- [ ] Implementation: logs view from file with interaction but no lazy loading
  - [ ] create sub-task...

(An actual github milestone is too heavy-weight for the 1-person planning I need.)
